### ISSUE TITLE
Displaying errors when user is using the Discord-version of SCP: SL

### ISSUE THREAD

**Issue by sinsa92** [galaxy119/DiscordIntegration#16] opened 2020-07-30 02:22 UTC
The bot will sometimes not display the logs correctly if the User is using the Discord version of SCP: SL. For Example:

Discord-User:
![grafik](https://user-images.githubusercontent.com/36137659/88873077-20d57a00-d21c-11ea-9954-5e72d39a1f99.png)

Steam-User:
![grafik](https://user-images.githubusercontent.com/36137659/88873090-2af77880-d21c-11ea-8518-69ccb312bc6a.png)

**Comment by galaxy119** [comment] 2020-07-30 18:15
Blame the base game for using # as the separator for ra messages, instead of 2 separate strings, and for including the #xxxx numbers of people's discord Id's in their name for some reason. This likely can't be fixed without a rewrite of the ra message handler by nw, since that is what the plugin has to use in order to transmit messages to the bot for both events and command responses.

**Closed by galaxy119** 2020-07-30 18:15 UTC

**Comment by sinsa92** [comment] 2020-07-30 22:39
Wouldn't it be possible to fetch the user by the discord id and then get the Tag (Name#Discriminator) via that? I think most discord libraries do that.

**Comment by galaxy119** [comment] 2020-07-31 11:46
That isn't the issue, the issue is that the server itself contains the '#' symbol, which the game considers to be the splitter symbol for RA messages.

Source#Message

When multiple #'s are in the string, it uses the last one as the seperator.
So

Plugin#1234567890#12345 has killed someone
gets turned into
12345 has killed someone
by SCP:SL. I'll have to re-write the entire way the plugin communicates to the bot in order to fix that.
